### ISSUE TITLE
Support scripts with prefix names

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/p-s#24]
Given I have these scripts:

```javascript
module.exports = {
  scripts: {
    thing: 'echo "thing"',
    things: 'echo "things"',
  },
}
```

It is impossible for me to run the `things` script because the prefix resolver will resolve to the `things` script. This may be something that @rowanoulton needs to fix in [`prefix-matches`](https://github.com/rowanoulton/prefix-matches). This would be acceptable behavior:

1. `npm start thing` runs `thing`
2. `npm start t` runs `thing`
3. `npm start things` runs `things`

This would be a breaking change.

**Comment by rowanoulton** [comment]
Hey, sorry for the delay on this one.

Interesting problem, perhaps I can look at giving direct matches precedence in `prefix-matches`. That sounds like it would solve the problem?

**Comment by kentcdodds** [comment]
Yeah, that would solve 1 and 3, but not 2. What do you think about # 2?

**Comment by kentcdodds** [comment]
Because this is a breaking change, whoever makes the PR for this feature, please make it to the [`next` branch](https://github.com/kentcdodds/p-s/tree/next) so we can get a few breaking changes in a single release.

**Comment by sxn** [comment]
How about sorting the matches alphabetically? Right now if I run prefix-matches with 
```
{
  foobar: {
    script: 'foobar'
  },
  foo: {
     script: 'foo'
  }
}
```
I will get back ```[{ script: 'foobar' }, { script: 'foo' }]```. If [https://github.com/rowanoulton/prefix-matches/blob/master/prefix.js#L29](matches) would just be sorted alphabetically, the result would be ```[{ script: 'foo' }, { script: 'foobar' }]```, which is fine because [https://github.com/kentcdodds/p-s/blob/master/src/get-script-to-run.js#L22](getScriptString) only uses the first result anyway.

This might introduce some other cases that might look odd though, such as:
```
{
  testing: {
    script: 'testing'
  },
  test: {
     script: 'test'
  },
  tests: {
     script: 'tests'
  },
}
```
leading to ```[{ script: 'test' }, { script: 'testing' }, { script: 'tests' }]```.

If you think this behavior is acceptable, I could open PRs for both repositories. :sweat_smile:

**Comment by kentcdodds** [comment]
Yeah, I'm honestly not sure what to do about this. It's a little tough. If you think that it'd be an improvement this way then I'm happy to discuss it. I'd like to get some solid test cases/docs to get a good idea of how this works. Thanks!

**Comment by sxn** [comment]
I'm...also not sure. On the one hand just adding a ```.sort()``` to ```prefix.js``` would bring the specified behaviour. On the other hand I'm not sure if that change is needed or, indeed, wanted in that repository?

Another question is: have you (or anyone else) encountered this limitation in your workflow? I tend to not have similarly named scripts, and whatever examples I could come up with off the top of my can very easily be solved by the nesting feature. :smile:

**Comment by kentcdodds** [comment]
Actually, another thing to consider would be maybe retrofitting my new [match-sorter](https://github.com/kentcdodds/match-sorter) to work with this. All I think it would take is the ability to configure it to treat `.` and `-`as word separators and we'd probably be good... Though that might be a little much................. Yeah... Probably.

**Comment by sxn** [comment]
Maaaaaaybe a bit much :smile:

**Comment by pvinis** [comment]
How about if the script im trying to run exists as it is, then run this, otherwise do some "smart" thing?
I have `iosX` and `ios`, and running `nps i`, `nps ios` and `nps iosX`, all run `iosX`. The correct behavior would be that `nps ios` should run `ios`, because there is a script with the exact name.

**Comment by kentcdodds** [comment]
Hmmmmm.... That's how it should be working. If it's not, that's a bug. Would you like to open a new issue about it with a reproduction repository?

**Comment by pvinis** [comment]
https://github.com/kentcdodds/nps/issues/191
here you go, i also added a repo.
