### ISSUE TITLE
Write e2e tests

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/p-s#31]
As suggested by @nkbt in #30. Maybe we could use [`nixt`](https://github.com/vesln/nixt).

**Comment by nkbt** [comment]
I'll take it. Want to try nixt as it looks pretty sick. Hopefully will get some base tests out later today

**Comment by kentcdodds** [comment]
Sweet. I've never used nixt. Looking forward to what you come up with!

**Comment by nkbt** [comment]
Hm nixt does not seem to work properly for me. Spent a bit of time with it, but no luck yet.

https://github.com/vesln/nixt/issues/16

Maybe I will go with bash then for the moment, or look for some nicer alternative... Not today tho

**Comment by kentcdodds** [comment]
Cool. See if you can make it work cross-platform so we don't shut out windows users.

**Comment by nkbt** [comment]
That might be a concern, though I expected to run e2e on CI to begin with. Generally I doubt it is possible to do completely cross-platform CLI testing, since shell scripts will be running in background anyway =(.

**Comment by kentcdodds** [comment]
Makes sense. I think we're OK if it's only running in CI

**Comment by nkbt** [comment]
Since nixt is not really working and writing shell scripts at home on my Windows was not an easy option, I  fixed a [cli-tester](https://npm.im/cli-tester). Not particularly a rocket science thingy...

Had some fun making it work smoothly on all Node versions down to 0.10 (so it is ok with `p-s` matrix build).

Welcome =)

**Comment by kentcdodds** [comment]
Cool! Looking forward to seeing the pull request!
